steps:
# build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/doom-engine', '.']
    # push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/doom-engine']
    # Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'doom-engine', '--image', 'gcr.io/$PROJECT_ID/doom-engine', '--region', 'us-central1']
images:
- gcr.io/$PROJECT_ID/doom-engine